### PR TITLE
Remove testdata

### PR DESCRIPTION
**Pull request by cjauvin**
The idea is to remove `testdata` and use the same mechanism as RavenPy to deal with a local copy of `raven-testdata`.

Depends on: https://github.com/Ouranosinc/raven-testdata/pull/6

### CODE REVIEW

**Review by huard — APPROVED** [review]

**Review by Zeitsperre — APPROVED** [review]
That a lot of removed lines. Nice.

**Comment by tlvu** [comment]
I haven't seen any notebooks modified.  The notebooks are currently accessing those files locally using https://github.com/Ouranosinc/raven/blob/766a288d282b99f097d0d2e0e4a31adf25b8d72c/docs/source/notebooks/example_data.py

I think what @huard wants is for all the notebooks to directly access all those `.nc` files on Thredds at https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/catalog/birdhouse/testdata/raven/catalog.html.

The files on Thredds are being automatically synced from `raven-testdata` using https://github.com/bird-house/birdhouse-deploy/blob/4c22f39cd0a20e66ec56dea89b44847971a9c485/birdhouse/deployment/deploy-data-raven-testdata-to-thredds.yml#L1-L12

The notebooks here are also being automatically synced from this repo to production PAVICS using https://github.com/bird-house/birdhouse-deploy/blob/4c22f39cd0a20e66ec56dea89b44847971a9c485/birdhouse/components/scheduler/config.yml.template#L13-L27 so the all the notebooks should be updated before this PR is merged.

**Comment by cjauvin** [comment]
@huard @tlvu Je viens de remplacer tous les `TESTDATA` dans les notebooks par des appels à `raven.tutorial.get_file`. Je n'ai pas roulé les notebooks par contre, car ça a plus de sens que David s'en charge, s'il est toujours d'accord.

Notez qu'il reste celui-ci à caser : https://github.com/Ouranosinc/raven/blob/master/tests/testdata/solution.rvc

Je l'avais hard-codé dans une string et une fixture dans RavenPy et raven mais comme il semble être pas mal en demande ça serait probablement mieux de lui trouver une place dans `raven-testdata`. Par contre je sais pas dans quelle section il serait plus approprié (et le mettre dans le root je pense pas que ça une bonne idée). J'attends vos instructions pour updater là où ça s'applique.

**Comment by huard** [comment]
`gr4j_cemaneige`

**Comment by tlvu** [comment]
oh `raven.tutorial.get_file` so Thredds is not even needed.  So @huard do we still need to sync the `.nc` files to Thredds since they are un-used?

**Comment by tlvu** [comment]
Houston we have a problem, dans l'environment Jupyter `ModuleNotFoundError: No module named 'raven'`.

**Comment by cjauvin** [comment]
> Houston we have a problem, dans l'environment Jupyter `ModuleNotFoundError: No module named 'raven'` (http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/890/console)

Est-ce qu'on peut le pip installer dans l'environnement où roule note book?

**Comment by tlvu** [comment]
> > Houston we have a problem, dans l'environment Jupyter `ModuleNotFoundError: No module named 'raven'` (http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/890/console)
> 
> Est-ce qu'on peut le pip installer dans l'environnement où roule note book?

Been thinking about this over the weekend.  @huard Is ravenpy to raven as xclim is to finch?  If yes, then should we move that `tutorial.get_file` to ravenpy then install ravenpy in the Jupyter env?

**Comment by Zeitsperre** [comment]
> > > Houston we have a problem, dans l'environment Jupyter `ModuleNotFoundError: No module named 'raven'` (http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/890/console)
> > 
> > 
> > Est-ce qu'on peut le pip installer dans l'environnement où roule note book?
> 
> Been thinking about this over the weekend. @huard Is ravenpy to raven as xclim is to finch? If yes, then should we move that `tutorial.get_file` to ravenpy then install ravenpy in the Jupyter env?

@tlvu I think we can safely say that your comparison is right. RavenPy is the internal functions of Raven, so moving the `get_file` functions there should be done.

**Comment by cjauvin** [comment]
I'm closing this PR as it crashes the doc generation and so I don't want to merge it in master. Instead, I have merged it into: https://github.com/Ouranosinc/raven/tree/fix-337

**Comment by tlvu** [comment]
@cjauvin Can this branch `remove-testdata` be removed to avoid cluttering the repo?

**Comment by cjauvin** [comment]
@tlvu deleted

**Pull request closed without merging**
