### PR TITLE
Fix 116

### LINKED ISSUE #116: PEP8 and HBVEC model tests are failing
The master branch is currently failing due to inaccurate outputs from the HBVEC process tests as well as from a bunch of PEP8 violations. I can deal with the PEP8 syntax but could @huard or @richardarsenault see why the hydro model outputs aren't accurate?

Opening an issue here now to open a new branch dealing with both those problems.

### PR DESCRIPTION
**Pull request by Zeitsperre**
## Overview

This PR fixes #116 

Changes:

* Changes to code base to satisfy PEP8
* Adjustment to HBVEC model to pass tests

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@julemai The failing tests for the HBVEC model are a total mystery to me. Do you think you could look into this? If you're short on time, I'm tempted to skip them so that we can have a passing build of the master branch. Thanks!

**Comment by julemai** [comment]
@Zeitsperre All tests still fail on my side with:
```
______________________________________ ERROR collecting tests/test_LHMP_models.py ______________________________________
ImportError while importing test module '/Users/j6mai/Documents/GitHub/raven/tests/test_LHMP_models.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_LHMP_models.py:5: in <module>
    from raven import models
raven/__init__.py:5: in <module>
    from .wsgi import application
raven/wsgi.py:4: in <module>
    from .processes import processes
raven/processes/__init__.py:7: in <module>
    from .wps_generic_shape_properties import ShapePropertiesProcess
raven/processes/wps_generic_shape_properties.py:1: in <module>
    import fiona
E   ModuleNotFoundError: No module named 'fiona'
```

And `make install` yields:
```
Installing Anaconda ...
Updating conda environment raven ...
"/Users/j6mai/miniconda/bin/conda" create --yes -n raven python=3.6

CondaValueError: prefix already exists: /Users/j6mai/miniconda/envs/raven

make: *** [conda_env] Error 1
```

I'm installing everything from scratch right now. Give me a minute and I will look into this once the environment is installed.

**Comment by Zeitsperre** [comment]
That's frustrating. Let me know if this is still an issue with a clean installation. The makefiles should work without issue for all current pull releases in clean systems, macOS and Linux.

**Comment by huard** [comment]
The "reference" makefile is here: 
https://github.com/bird-house/cookiecutter-birdhouse/blob/master/%7B%7Bcookiecutter.project_repo_name%7D%7D/Makefile

Ideally we'd stick to it, with our own custom additions.

**Comment by julemai** [comment]
There are actually three tests failing for me:
```
tests/test_emulators.py::TestGR4JCN::test_simple FAILED
tests/test_emulators.py::TestHBVEC_OST::test_simple FAILED    
tests/test_wps_ostrich_hbv_ec.py::TestOstrichHBVECProcess::test_simple FAILED
```

And it crashes completely for test `tests/test_wps_raven_multi_model.py::test_graph_ensemble_uncertainty` with
```
tests/test_wps_raven_multi_model.py::test_graph_ensemble_uncertainty bash: line 1:  2724 Abort trap: 6           pytest -v -m 'not slow and not online'
make: *** [test] Error 134
```

I can't do a lot without seeing any debugging message and not knowing where the Raven tests etc are built... Sorry!

**Comment by Zeitsperre** [comment]
I just adjusted the `.common` import in that test. There was a space before that maybe your interpreter couldn't handle properly. Here's hoping.

**Comment by julemai** [comment]
Hm. Still crashes with:
```
tests/test_wps_raven_multi_model.py::test_graph_ensemble_uncertainty bash: line 1:  3997 Abort trap: 6           pytest -v -m 'not slow and not online'
make: *** [test] Error 134
```

First test `tests/test_wps_raven_multi_model.py::test_raven_multi_model_process` in this module is passing though. So, shouldn't be the import....

**Comment by julemai** [comment]
Resolved the GR4J and HBV-EC failing tests (see [commit](https://github.com/Ouranosinc/raven/commit/697d87a73d8253e5d558daa48f85b129f6a7f824) for details)

BUT I had to skip two tests in the `test_wps_raven_multi_model.py` where I don't know how to resolve this.

**Pull request merged**
