### PR TITLE
Added notebook for parallel parameters

### PR DESCRIPTION
**Pull request by richardarsenault**
Added notebook for parallel multi-parameter simulation. Works, but the resp_get asobj=True fails, I think because diagnostics is a zip file. But using asobj=False works. I'll aslo try the same method for the multi-basin, I think I can get that to work too.

### CODE REVIEW

**Comment by richardarsenault** [comment]
I see you were able to make it work with asobj=True, but on my side it still fails.

**Comment by huard** [comment]
Should work with birdy 0.6.3

**Comment by richardarsenault** [comment]
@huard This one still fails for me, I still get an error at line:
[hydrograph, storage, solution, diagnostics] = resp.get(asobj=True)



> AttributeError                            Traceback (most recent call last)
> <ipython-input-3-a2bbe24e4180> in <module>
> ----> 1 [hydrograph, storage, solution, diagnostics] = resp.get(asobj=True)
>       2 hydrograph
> 
> ~/src/birdy/birdy/client/outputs.py in get(self, asobj)
>      32             # TODO: add reason for failure
>      33             raise ProcessFailed("Sorry, process failed.")
> ---> 34         return self._make_output(asobj)
>      35 
>      36     def _make_output(self, convert_objects=False):
> 
> ~/src/birdy/birdy/client/outputs.py in _make_output(self, convert_objects)
>      38                                                                              self.processOutputs])
>      39         Output.__repr__ = utils.pretty_repr
> ---> 40         return Output(*[self._process_output(o, convert_objects) for o in self.processOutputs])
>      41 
>      42     def _process_output(self, output, convert_objects=False):
> 
> ~/src/birdy/birdy/client/outputs.py in <listcomp>(.0)
>      38                                                                              self.processOutputs])
>      39         Output.__repr__ = utils.pretty_repr
> ---> 40         return Output(*[self._process_output(o, convert_objects) for o in self.processOutputs])
>      41 
>      42     def _process_output(self, output, convert_objects=False):
> 
> ~/src/birdy/birdy/client/outputs.py in _process_output(self, output, convert_objects)
>      57 
>      58         if convert_objects:
> ---> 59             return convert(output, self._path, self._converters, self.verify)
>      60         else:
>      61             return output.reference
> 
> ~/src/birdy/birdy/client/converters.py in convert(output, path, converters, verify)
>     265             out = converter.convert()
>     266             if converter.nested:  # Then the output is a list of files.
> --> 267                 out = [convert(o, path) for o in out]
>     268             return out
>     269 
> 
> ~/src/birdy/birdy/client/converters.py in <listcomp>(.0)
>     265             out = converter.convert()
>     266             if converter.nested:  # Then the output is a list of files.
> --> 267                 out = [convert(o, path) for o in out]
>     268             return out
>     269 
> 
> ~/src/birdy/birdy/client/converters.py in convert(output, path, converters, verify)
>     271             pass
>     272 
> --> 273     warnings.warn(UserWarning("No converter was found for {}".format(output.identifier)))
>     274     return output.reference
>     275 
> 
> AttributeError: 'str' object has no attribute 'identifier'

**Comment by richardarsenault** [comment]
Yep, works, thanks!

**Pull request merged**
