### PR TITLE
tests + notebooks: use new official NCML link

### PR DESCRIPTION
**Pull request by tlvu**
"birdhouse/1-Datasets" was the first version and won't receive auto NCML deploy update anymore.

Will be removed eventually to avoid future confusions.

### CODE REVIEW

**Comment by tlvu** [comment]
@richardarsenault `test_bias_correction.py` is working in the current Travis-CI build.  I've bumped the timeout in the front proxy in https://github.com/bird-house/birdhouse-deploy/pull/61.

@tlogan2000 I've removed all the old `birdhouse/1-Datasets` references in Raven in this PR.  Do you know if it is used somewhere else?  If not, we can remove it from our Thredds server.

**Comment by tlogan2000** [comment]
@tlvu there is one small test failing?  Does not seem likely that it is related to this PR though...

**Comment by tlogan2000** [comment]
> @tlogan2000 I've removed all the old `birdhouse/1-Datasets` references in Raven in this PR. Do you know if it is used somewhere else? If not, we can remove it from our Thredds server.

I think you should be able to remove birdhouse/1-Datasets

**Comment by tlogan2000** [comment]
failing tests see due to the  refactoring that Pascal and David have done .... `xclim.generic` no longer exists.  Will need to find where `get_dist` is located.  Likely in `xclim.core`?

**Comment by tlogan2000** [comment]
> failing tests see due to the refactoring that Pascal and David have done .... `xclim.generic` no longer exists. Will need to find where `get_dist` is located. Likely in `xclim.core`?

@tlvu `from xclim.indices.generic import get_dist`

**Comment by tlvu** [comment]
I just realized old `birdhouse/1-Datasets` reference is still on `master` branch of Raven.

How much work left to merge this branch?  Else I'll have to duplicate this change on `master` manually before I can remove `birdhouse/1-Datasets` from our Thredds server.

**Comment by richardarsenault** [comment]
@tlvu Do you mean the bias_correction branch? or the master branch prior to making a release? I am not sure I understand, sorry!

**Comment by tlvu** [comment]
> Do you mean the bias_correction branch? or the master branch prior to making a release? I am not sure I understand, sorry!

Yes sorry for being unclear, branch `bias_correction`.

**Comment by richardarsenault** [comment]
OK! I think we can merge with the changes you've made to the Thredds link. We can then make a new branch to continue development on it. Is that reasonable?

**Comment by tlvu** [comment]
> OK! I think we can merge with the changes you've made to the Thredds link. We can then make a new branch to continue development on it. Is that reasonable?

That would be great.  So I'll merge this branch to your `bias_correction` branch, then I'll let you merge `bias_correction` to `master`.

**Comment by tlvu** [comment]
> > failing tests see due to the refactoring that Pascal and David have done .... `xclim.generic` no longer exists. Will need to find where `get_dist` is located. Likely in `xclim.core`?
> 
> @tlvu `from xclim.indices.generic import get_dist`

@tlogan2000 I think the needed change is already on `master`.  The failing tests will probably just work once this `bias_correction` branch is merged to `master`.

```bash
$ git diff ..master raven/utilities/graphs.py
diff --git a/raven/utilities/graphs.py b/raven/utilities/graphs.py
index 400488a..bb2b255 100644
--- a/raven/utilities/graphs.py
+++ b/raven/utilities/graphs.py
@@ -293,10 +293,10 @@ def ts_fit_graph(ts, params):
     -------
     fig
     """
-    from xclim.generic import get_dist
+    from xclim.indices.generic import get_dist
 
     n = ts.nbasins.size
-    dist = params.attrs['standard_name'].split(' ')[0]
+    dist = params.attrs['scipy_dist']
 
     fig, axes = plt.subplots(n, figsize=(10, 6), squeeze=False)
```

**Comment by tlogan2000** [comment]
Ok parfait.  Sorry hadn't noticed that the pr was for a branch other master
________________________________
De : Long Vu <notifications@github.com>
Envoyé : 22 juillet 2020 14:27
À : Ouranosinc/raven <raven@noreply.github.com>
Cc : Logan, Travis <Logan.Travis@ouranos.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Ouranosinc/raven] tests + notebooks: use new official NCML link (#291)


failing tests see due to the refactoring that Pascal and David have done .... xclim.generic no longer exists. Will need to find where get_dist is located. Likely in xclim.core?

@tlvu<https://github.com/tlvu> from xclim.indices.generic import get_dist

@tlogan2000<https://github.com/tlogan2000> I think the needed change is already on master. The failing tests will probably just work once this bias_correction branch is merged to master.

$ git diff ..master raven/utilities/graphs.py
diff --git a/raven/utilities/graphs.py b/raven/utilities/graphs.py
index 400488a..bb2b255 100644
--- a/raven/utilities/graphs.py
+++ b/raven/utilities/graphs.py
@@ -293,10 +293,10 @@ def ts_fit_graph(ts, params):
     -------
     fig
     """
-    from xclim.generic import get_dist
+    from xclim.indices.generic import get_dist

     n = ts.nbasins.size
-    dist = params.attrs['standard_name'].split(' ')[0]
+    dist = params.attrs['scipy_dist']

     fig, axes = plt.subplots(n, figsize=(10, 6), squeeze=False)

**Pull request merged**
