### PR TITLE
Ostrich wps

### LINKED ISSUE #16: Wrap existing model calibration algorithms as WPS (8)
Challenge is to connect calibration algorithms to model description through WPS to avoid the calibration algorithm having to call WPS services to get model outputs (the overhead would kill us).

### PR DESCRIPTION
**Pull request by julemai**
## Overview

This PR fixes #16 

Changes:

* Added OSTRICH emulation of GR4J, MOHYSE, HMETS, and HBV-EC

### CODE REVIEW

**Comment by julemai** [comment]
I think some of the current tests are producing a `Raven_errors.txt` in the main folder. With the error message `ERROR : A model input file name must be supplied as an argument to the Raven executable.`. This indicates that somewhere raven is executed without proper command line arguments, i.e., a base name of the `.rv*` files. I think one of these tests is `TestGR4JCN.test_simple` but I can't identify where RAVEN is called without command-line argument here.

**Comment by huard** [comment]
Hi Julie, I can't find the error you're mentioning. I've removed the printout from ostrich and although all test fails, it's because the comparisons with expected parameters doesn't match, not because ostrich errored. Could you direct me to the problem you're seeing ?

**Comment by julemai** [comment]
When 

> Hi Julie, I can't find the error you're mentioning. I've removed the printout from ostrich and although all test fails, it's because the comparisons with expected parameters doesn't match , not because ostrich errored. 

Which expected parameters do not match?? When I run`make test` everything is fine.

> Could you direct me to the problem you're seeing ?

When I run `make test` (on the terminal when being located in `~/path/GitHub/raven/` there is a `Raven_errors.txt` popping up in this folder. The file gets first created by the `tests/test_emulators.py::TestGR4JCN_OST::test_simple`. But following tests might have the same issue... I don't know where this is coming from. The error file only will get created when RAVEN is executed without its command line argument, e.g. `./raven.exe raven-hbv-ec` without the `raven-hbv-ec`.

**Comment by julemai** [comment]
> When
> 
> > Hi Julie, I can't find the error you're mentioning. I've removed the printout from ostrich and although all test fails, it's because the comparisons with expected parameters doesn't match , not because ostrich errored.
> 
> Which expected parameters do not match?? When I run`make test` everything is fine.
> 
> > Could you direct me to the problem you're seeing ?
> 
> When I run `make test` (on the terminal when being located in `~/path/GitHub/raven/`) there is a `Raven_errors.txt` popping up in this source folder. I only realized that because git told me that a new file got created and wanted to commit it. The file gets first created by the `tests/test_emulators.py::TestGR4JCN_OST::test_simple`. But following tests might have the same issue... I don't know where this is coming from. The error file only will get created when RAVEN is executed without its command line argument, e.g. `./raven.exe raven-hbv-ec` without the `raven-hbv-ec`.

**Comment by huard** [comment]
For me all Ostrich related tests fail... is it possible that the random number generator on Mac and Linux is different and that would ruin results ?

For example: 
```
================================================================================================= FAILURES =================================================================================================
____________________________________________________________________________________ TestOstrich.test_gr4j_with_no_tags ____________________________________________________________________________________
Traceback (most recent call last):
  File "/home/david/src/raven/tests/test_base.py", line 66, in test_gr4j_with_no_tags
    err_msg='calibrated parameter set is not matching expected value')
  File "/home/david/.conda/envs/raven/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 568, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/home/david/.conda/envs/raven/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 964, in assert_array_almost_equal
    precision=decimal)
  File "/home/david/.conda/envs/raven/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 780, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 4 decimals
calibrated parameter set is not matching expected value
(mismatch 100.0%)
 x: array([  0.4434,   7.0125, 146.5454,   6.3245,  17.7584,   0.2306])
 y: array([  2.4247,   3.759 , 204.3856,   5.8669,  16.6041,   0.3728])
```

**Comment by julemai** [comment]
Hm. Weird. I would have thought that this is exactly the same on all platforms... I wouldn't have committed all this if the tests wouldn't succeed. 

I can look into that but not before next week.

**Comment by huard** [comment]
Ostrich uses `srand` whose implementation relies on system libraries. 
However, `Utility.cpp` in Ostrich seems to include code to parse a `OstRandomNumbers.txt` file. I assume that we could pass our own pre-generated random number file, which would allow us to test we get the same results. I see no mention of that in the documentation though...

**Comment by julemai** [comment]
This should indeed exist and would be the way to go. I have to finish up three other projects before I can get onto this again. I will contact Shawn to get a bit more details.

**Comment by julemai** [comment]
It should work now. [commit](https://github.com/Ouranosinc/raven/commit/af0d9a4608b9bde9eab4e2021cbed019a4ad07bb)

@huard Could you please make sure that the file `OstRandomNumbers.txt` that I've added to all `tests/testdata/ostrich-*` and `raven/models/ostrich-*` is copied. But it should only be copied for our tests. For a real run (that was requested by a user) this file should not be copied. Ostrich always reads random numbers from a file when this file exists.

Also the line `RandomSeed` in the `ostIn.txt` should only be there when we run our tests. the line should not be there when we run Ostrich for real (for the user).

When the file `OstRandomNumbers.txt` does not exist and the `RandomSeed` is not specified, the calibration is purely random. And this is the behaviour we actually want.

**Comment by huard** [comment]
@julemai 
Hey, it' monday morning ! When did you do this ?

Will do.

**Comment by huard** [comment]
@Zeitsperre The build is failing in the conda_env section of the make install. Any idea ?

**Comment by huard** [comment]
@Zeitsperre  Forget it, I think I know got it.

**Comment by julemai** [comment]
Nice!! Currently 5 tests are failing on my side and this `raven_errors.txt` in the main folder still gets produced:

```
_________________________________________________ TestOst.test_random __________________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_rv.py", line 104, in test_random
    assert o.comment_random == '#'
AssertionError: assert None == '#'
  -None
  +'#'
_____________________________________ TestOstrichGR4JCemaNeigeProcess.test_simple ______________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_wps_ostrich_gr4j_cemaneige.py", line 62, in test_simple
    assert_response_success(resp)
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/tests.py", line 121, in assert_response_success
    assert len(success) == 1
AssertionError
------------------------------------------------- Captured stderr call -------------------------------------------------
Traceback (most recent call last):
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/app/Process.py", line 200, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/Users/j6mai/Documents/GitHub/raven/raven/processes/wps_raven.py", line 62, in _handler
    model.assign(name, data)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 187, in assign
    raise AttributeError("No configuration key named {}".format(key))
AttributeError: No configuration key named MaxEvals
_________________________________________ TestOstrichHBVECProcess.test_simple __________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_wps_ostrich_hbv_ec.py", line 63, in test_simple
    assert_response_success(resp)
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/tests.py", line 121, in assert_response_success
    assert len(success) == 1
AssertionError
------------------------------------------------- Captured stderr call -------------------------------------------------
Traceback (most recent call last):
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/app/Process.py", line 200, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/Users/j6mai/Documents/GitHub/raven/raven/processes/wps_raven.py", line 62, in _handler
    model.assign(name, data)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 187, in assign
    raise AttributeError("No configuration key named {}".format(key))
AttributeError: No configuration key named MaxEvals
_________________________________________ TestOstrichHMETSProcess.test_simple __________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_wps_ostrich_hmets.py", line 61, in test_simple
    assert_response_success(resp)
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/tests.py", line 121, in assert_response_success
    assert len(success) == 1
AssertionError
------------------------------------------------- Captured stderr call -------------------------------------------------
Traceback (most recent call last):
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/app/Process.py", line 200, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/Users/j6mai/Documents/GitHub/raven/raven/processes/wps_raven.py", line 62, in _handler
    model.assign(name, data)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 187, in assign
    raise AttributeError("No configuration key named {}".format(key))
AttributeError: No configuration key named MaxEvals
_________________________________________ TestOstrichMOHYSEProcess.test_simple _________________________________________
Traceback (most recent call last):
  File "/Users/j6mai/Documents/GitHub/raven/tests/test_wps_ostrich_mohyse.py", line 62, in test_simple
    assert_response_success(resp)
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/tests.py", line 121, in assert_response_success
    assert len(success) == 1
AssertionError
------------------------------------------------- Captured stderr call -------------------------------------------------
Traceback (most recent call last):
  File "/Users/j6mai/miniconda/envs/raven/lib/python3.6/site-packages/pywps/app/Process.py", line 200, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/Users/j6mai/Documents/GitHub/raven/raven/processes/wps_raven.py", line 62, in _handler
    model.assign(name, data)
  File "/Users/j6mai/Documents/GitHub/raven/raven/models/base.py", line 187, in assign
    raise AttributeError("No configuration key named {}".format(key))
AttributeError: No configuration key named MaxEvals
```

**Comment by huard** [comment]
@Zeitsperre Any idea why pytest runs 2.7 instead of 3.6 ?

**Comment by Zeitsperre** [comment]
Looking into this now.

**Comment by Zeitsperre** [comment]
@huard The python version wasn't being set in the `bootstrap` entry, which is why it wasn't installing properly. I've reverted many of the changes you made if that's alright. Using `language: generic` really speeds up the builds as `language: python` it installs a python after booting, which is irrelevant with Anaconda-based buildout. 

The GIS branch has a lot of small adjustments (feature creep) to the .travis.yml and Makefile. Once that PR is ready, we should have too many more problems.

**Comment by Zeitsperre** [comment]
Works now.

**Comment by huard** [comment]
Thanks !

**Comment by julemai** [comment]
Woohoo!! Makes my day

**Comment by huard** [comment]
Me too, this been a tough one. Working on the multi-model stuff now. Should be easier.

**Comment by julemai** [comment]
Good luck! I will be available for some minor things until end of April and then be back on in May

**Comment by huard** [comment]
Got it !

**Comment by richardarsenault** [comment]
Woohoo! Good work everyone! @huard, I have not forgotten for the multi-model inputs, working on this in the plane tomorrow.

**Pull request merged**
