### PR TITLE
requirements_dev.txt: notebook tests require package nc-time-axis

### PR DESCRIPTION
**Pull request by tlvu**
`make test-notebooks` error:

```
________________________________________________________________________ docs/source/notebooks/Bias_correcting_climate_data.ipynb::Cell 3 _________________________________________________________________________
Notebook cell execution failed
Cell 3: Cell execution caused an exception

Input:
import nc_time_axis
import cftime

group_month_nowindow = sdba.utils.Grouper('time.month')

Adj = sdba.DetrendedQuantileMapping(nquantiles=50, kind='+', group=group_month_nowindow)

Adj.train(ds_ref_sub['pr'],ds_his_sub['pr'])

Scen_pr = Adj.adjust(ds_fut_sub['pr'], interp="linear")

Adj.train(ds_ref_sub['tasmax'],ds_his_sub['tasmax'])

Scen_tasmax = Adj.adjust(ds_fut_sub['tasmax'], interp="linear")

Adj.train(ds_ref_sub['tasmin'],ds_his_sub['tasmin'])
Scen_tasmin = Adj.adjust(ds_fut_sub['tasmin'], interp="linear")

Traceback:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-7ce0cc47efec> in <module>
      1 # Apply the bias correction
----> 2 import nc_time_axis
      3 import cftime
      4
      5 # We will apply the statistics per month

ModuleNotFoundError: No module named 'nc_time_axis'
```

## Overview

This PR fixes [issue id]

Changes:

* Added ...

## Additional Information

Links to other issues or sources.

### CODE REVIEW

**Comment by tlvu** [comment]
Actually I also found `nc-time-axis` in `client_environment.yml`.  What is the purpose of this file?

My workflow to run the notebooks test are:

```sh
conda env create -f environment.yml
conda activate raven
make develop
make start
make test-notebooks
```

Still good?

**Comment by tlvu** [comment]
Notebooks error report, using the workflow from the previous comment https://github.com/Ouranosinc/raven/pull/348#issuecomment-770109726.

We are down to 3 errors and 2 warnings that probably are the root cause of the 36 cells failure.

@huard Looks like we are very close to get all the notebooks to pass, I am pretty stoked !!!

Note the wps server and notebook are both python 3.8 since launched from the same conda env.

@cjauvin there is one `RAVENPY_TESTDATA_PATH env variable is not set` left which is weird since I did pip install ravenpy with binaries and it did solve other similar errors.

```
platform linux -- Python 3.8.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
plugins: flake8-1.0.7, nbval-0.9.6, dependency-0.5.1, notebook-0.6.1                                                                                                                                               
collected 166 items 
36 failed, 128 passed, 2 skipped, 1 warning in 427.78s (0:07:07)
```

Bias_correcting_climate_data::ipynb
```
        **************************************************************                                                                                                                                             
        Path : /tmp/pywps_process_otibp521/exec/model/p00                                                                                                                                                          
        **************************************************************                                                                                                                                             
        ADVISORY : The required global parameter RAINSNOW_TEMP was autogenerated with value 0.150000                                                                                                               
ERROR : CTimeSeries::Initialize: time series forcing data not available at beginning of model simulation                                                                                                           
                                                                                                                                                                                                                   
                                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/pywps/app/Process.py", line 249, in _run_process                                                                                                   
    self.handler(wps_request, wps_response)  # the user must update the wps_response.                                                                                                                              
  File "/zstore/repos/raven/raven/processes/wps_raven.py", line 138, in _handler                                                                                                                                   
    self.run(model, ts, kwds)                                                                                                                                                                                      
  File "/zstore/repos/raven/raven/processes/wps_raven.py", line 103, in run                                                                                                                                        
    model(ts=ts, **kwds)                                                                                                                                                                                           
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/models/base.py", line 501, in __call__                                                                                                     
    raise e                                                                                                                                                                                                        
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/models/base.py", line 488, in __call__                                                                                                    
    self.parse_results()                                                                                                                                                                                           
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/models/base.py", line 541, in parse_results                                                                                                
    raise exc                                                                                                                                                                                                      
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/models/base.py", line 534, in parse_results                                                                                                
    fns = self._get_output(pattern, path=path)                                                                                                                                                                     
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/models/base.py", line 639, in _get_output                                                                                                  
    raise UserWarning("No output files for {} in {}.".format(pattern, path))                                                                                                                                       
UserWarning: No output files for test_bias_correction_HMETS*Hydrographs.nc in /tmp/pywps_process_otibp521/exec.     
```

Climatological_ESP_forecasting.ipynb: Many of these repeated warnings:
```
/home/lvu/.conda/envs/raven/lib/python3.8/zipfile.py:1517: UserWarning: Duplicate name: 'raven-gr4j-cemaneige.rvc'                                                                                                 
  return self._open_to_write(zinfo, force_zip64=force_zip64) 
```

Extract_geographical_watershed_properties::ipynb,
gridded_data_subset::ipynb,
Full_process_example_1::ipynb: many repeated same traceback:
```
Traceback (most recent call last):
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/pywps/app/Process.py", line 249, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/zstore/repos/raven/raven/processes/wps_nalcms_zonal_stats.py", line 151, in _handler
    raster_bytes = gis.get_raster_wcs(bbox, geographic=False, layer=raster_url)
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/utilities/gis.py", line 208, in get_raster_wcs
    wcs = WebCoverageService("http://boreas.ouranos.ca/geoserver/ows", version="2.0.1")
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/owslib/wcs.py", line 53, in WebCoverageService
    return wcs201.WebCoverageService_2_0_1.__new__(
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/owslib/coverage/wcsBase.py", line 47, in __new__
    obj.__init__(url, xml, cookies, auth=auth)
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/owslib/coverage/wcs201.py", line 67, in __init__
    self._capabilities = reader.read(self.url, self.timeout)
AttributeError: 'WebCoverageService_2_0_1' object has no attribute 'timeout'
```

Hydrological_hindcasting::ipynb,
Hydrological_realtime_forecasting::ipynb: many of those repeated warnings
```
/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/models/rv.py:368: UserWarning: Units are not what Raven expects for pr.
Actual: m
Expected: mm/d
Make sure to set linear_transform to perform conversion.
```

Perform_Regionalization::ipynb
```
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/pywps/app/Process.py", line 249, in _run_process                                                                                     
    self.handler(wps_request, wps_response)  # the user must update the wps_response.                                                                                                      
  File "/zstore/repos/raven/raven/processes/wps_regionalisation.py", line 146, in _handler                                                                                                    
    nash, params = read_gauged_params(model_name)                                                                                                         
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/utilities/regionalization.py", line 191, in read_gauged_params                     
    f = get_local_testdata(f"regionalisation_data/{model}_parameters.csv")                                                                                                                                        
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/utilities/testdata.py", line 39, in get_local_testdata                                                                                     
    raise RuntimeError("RAVENPY_TESTDATA_PATH env variable is not set")                                                                
RuntimeError: RAVENPY_TESTDATA_PATH env variable is not set  
```

**Comment by tlvu** [comment]
@cjauvin Looks like there are 2 paths in ravenpy that access the binaries and the one below is fixed by pip installing with binaries but the one I found in the previous comment https://github.com/Ouranosinc/raven/pull/348#issuecomment-770118401 is not fixed.

```
docs/source/notebooks/Bias_correcting_climate_data::ipynb::Cell 7 Traceback (most recent call last):                                                                                                               
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/pywps/app/Process.py", line 249, in _run_process                                                                                                   
    self.handler(wps_request, wps_response)  # the user must update the wps_response.                                                                                                                              
  File "/zstore/repos/raven/raven/processes/wps_raven.py", line 117, in _handler                                                                                                                                   
    model = self.model(request)                                                                                                                                                                                    
  File "/zstore/repos/raven/raven/processes/wps_raven.py", line 52, in model                                                                                                                                       
    return self.model_cls(workdir=self.workdir)                                                                                                                                                                    
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/models/emulators.py", line 171, in __init__                                                                                                
    super().__init__(*args, **kwds)                                                                                                                                                                                
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/models/emulators.py", line 49, in __init__                                                                                                 
    super().__init__(*args, **kwds)                                                                                                                                                                                
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/models/base.py", line 104, in __init__                                                                                                     
    raise RuntimeError(                                                                                                                                                                                            
RuntimeError: Could not find raven binary in PATH, and RAVENPY_RAVEN_BINARY_PATH env variable is not set 
```

**Comment by huard** [comment]
client_environment I think was meant to provide a slimmed down version of what is required to run the notebooks (not the server). It's not actually tested however, so your mileage might vary. But you should make sure that every dependency in there is part of your jupyter env. What i mean is that those dependencies are necessary, but may not be sufficient. 

I don't understand the timeout error. The timeout attribute was introduced in owslib 0.21 https://geopython.github.io/OWSLib/#id6

The warnings are known, I don't think they point to serious issues. I've made a not to investigate the zip thing.

**Review by huard — APPROVED** [review]
The major issue to resolve is the timeout error. Tweaking the version of owslib hopefully solves it.

**Comment by tlvu** [comment]
> I don't understand the timeout error. The timeout attribute was introduced in owslib 0.21 https://geopython.github.io/OWSLib/#id6

I have `owslib=0.22.0=pyhd8ed1ab_0`, so this missing timeout attrib error should not have happened, weird.

**Comment by tlvu** [comment]
> I don't understand the timeout error. The timeout attribute was introduced in owslib 0.21 https://geopython.github.io/OWSLib/#id6

@huard FYI, I might have found the cause, see https://github.com/geopython/OWSLib/pull/730/files#r567188656

**Comment by tlvu** [comment]
Perform_Regionalization.ipynb
```
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/pywps/app/Process.py", line 249, in _run_process                                                                                     
    self.handler(wps_request, wps_response)  # the user must update the wps_response.                                                                                                      
  File "/zstore/repos/raven/raven/processes/wps_regionalisation.py", line 146, in _handler                                                                                                    
    nash, params = read_gauged_params(model_name)                                                                                                         
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/utilities/regionalization.py", line 191, in read_gauged_params                     
    f = get_local_testdata(f"regionalisation_data/{model}_parameters.csv")                                                                                                                                        
  File "/home/lvu/.conda/envs/raven/lib/python3.8/site-packages/ravenpy/utilities/testdata.py", line 39, in get_local_testdata                                                                                     
    raise RuntimeError("RAVENPY_TESTDATA_PATH env variable is not set")                                                                
RuntimeError: RAVENPY_TESTDATA_PATH env variable is not set  
```

related to https://github.com/CSHS-CWRA/RavenPy/issues/51

**Pull request merged**
