### PR TITLE
Clean up failing tests

### PR DESCRIPTION
**Pull request by huard**
## Overview
Failing tests on master were due to unfinished implementation of random seed refactor, and the hmets identifier - _ switch. 

In principle, all tests should pass locally, we now need to make sure they pass on Travis-CI as well.

### CODE REVIEW

**Comment by richardarsenault** [comment]
I confirm that tests are now all passing!

**Comment by julemai** [comment]
I still get the following error for all test:
```
ModuleNotFoundError: No module named 'fiona'
```

And `make install` is throwing:
```
make install
Installing Anaconda ...
Updating conda environment raven ...
"/Users/j6mai/miniconda/bin/conda" create --yes -n raven python=3.6

CondaValueError: prefix already exists: /Users/j6mai/miniconda/envs/raven

make: *** [conda_env] Error 1
```

**Comment by richardarsenault** [comment]
@julemai make install is working for me within this branch. Probably something to do with the makefile on MacOS?

**Comment by julemai** [comment]
No idea. It was working properly before- especially after I removed the old folder `/Users/j6mai/miniconda/` but this doesn't help anymore. :(

**Comment by huard** [comment]
@julemai Thanks for the report. Our makefile clearly needs some love. Will look into it.

**Comment by Zeitsperre** [comment]
It should work better now.

**Comment by Zeitsperre** [comment]
@tlvu and I looked this over. The makefile is now set up to install Anaconda at ~/miniconda3 if there isn't an existing conda installation. This workaround shouldn't mess with previously-installed Anaconda versions.

**Comment by julemai** [comment]
I still get exactly the same error when I run `make install`:

```
[j6mai@JulieUW:/Users/j6mai/Documents/GitHub/raven/]:
make install
Installing Anaconda ...
Updating conda environment raven ...
"/Users/j6mai/miniconda/bin/conda" create --yes -n raven python=3.6

CondaValueError: prefix already exists: /Users/j6mai/miniconda/envs/raven

make: *** [conda_env] Error 1
```

**Comment by richardarsenault** [comment]
I just did a test with a brand new dedicated computer and also had this fail. What I did was first call "make env_clean" before, then make install works. it does not work on master yet however.

**Comment by richardarsenault** [comment]
@huard I suggest we merge this PR and start another for the MacOS environment error for make install, it'll simplify the rest.

**Pull request merged**
