### PR TITLE
Allow restarts and define initial conditions [WIP]

### PR DESCRIPTION
**Pull request by huard**
## Overview

This PR related to #261 

Changes:

* Added method `resume` to replace RVC with solution file.
* Started working on templating initial conditions [WIP]

## Additional Information

Links to other issues or sources.

### CODE REVIEW

**Comment by richardarsenault** [comment]
This is great! I like the model.resume() method. Question though: Can we pass a "model" instance through WPS? Like can I do a first pass, then call a WPS with the model state as an input to the WPS function to hot-start the model in the WPS?

**Comment by huard** [comment]
No, but we could pass the solution file. This is not supported from WPS yet, but fairly easy (a ComplexInput `solution` to wpsio, then run resume on this file).

**Comment by richardarsenault** [comment]
OK awesome. Can you setup this logic? I can pass the rvc file through wpsio etc., but can you pass the rvc file to the resume method?

**Comment by huard** [comment]
Done, but untested.

**Comment by richardarsenault** [comment]
I am having trouble finding an elegant way to test this without calling multiple functions. I have an Idea, maybe it's not too complex to add:

Could we simply add a parameter in the inputs to the hydrological model (such as ts, params, start_date, etc.) that would be "initial_state" and that would take a path to a file (and default to None)? That way all our current logic stays the same and we could simply pass that argument whenever we call the model. It would make it more streamlined I think, rather than setting up a model instance, THEN calling the resume method, etc.

Just an idea, if it's not possible or too complex I'll work with what we have! Thanks!

**Comment by huard** [comment]
@richardarsenault See last commit.

**Comment by richardarsenault** [comment]
IS it possible you forgot to push a file named "states.py" or something like that, because the line 6 in rv.py is failing:

from . state import HRUStateVariables, BasinStateVariables

No module named 'raven.models.state'

Does that sound plausible?

Thanks

**Comment by huard** [comment]
Yes indeed. Will do.

Le dim. 17 mai 2020 12 h 05, richardarsenault <notifications@github.com> a
écrit :

**Comment by huard** [comment]
@julemai Some rvc files have
```
:BasinInitialConditions
:Attributes, Q
:Units , m3/s
1 , 3.6
:EndBasinInitialConditions
```
But `Q` is not in the solution file per say (only `Qout`, `Qlat`, `Qin`).  

Is `BasinInitialConditions` part of `BasinStateVariables` or it's independent ?

**Comment by julemai** [comment]
> @julemai Some rvc files have
> 
> ```
> :BasinInitialConditions
> :Attributes, Q
> :Units , m3/s
> 1 , 3.6
> :EndBasinInitialConditions
> ```
> 
> But `Q` is not in the solution file per say (only `Qout`, `Qlat`, `Qin`).
> 
> Is `BasinInitialConditions` part of `BasinStateVariables` or it's independent ?

I talked with James. He said "`Qout` is the same as `Q` in this context. " and "`:BasinInitialConditions` is like the low-power version of `:BasinStateVariables`. It only overwrites the instantaneous flow Qout/Q".

**Pull request merged**
