### PR TITLE
Setup cruft to refresh project from cookiecutter

### PR DESCRIPTION
**Pull request by tlvu**
## Overview

This PR fixes https://github.com/Ouranosinc/raven/issues/187 and requires PR https://github.com/bird-house/cookiecutter-birdhouse/pull/85

This PR is part of issue https://github.com/bird-house/cookiecutter-birdhouse/issues/61

Changes:

* Settle down for `cruft` but configs for `scaraplate` and `cookiecutter_project_upgrader` are left in history for reference.  See PR https://github.com/bird-house/cookiecutter-birdhouse/pull/85 for why `cruft` was chosen.

* cruft notes:
  * cookiecutter commit used is recorded so we know when it was used
  * the skip file list are for files we know will diverge significantly and it's not worth keeping in sync (ex: all the hello examples not worth keeping, the `environment.yml` `requirements.txt` of each different project can not be identical, same for the list of processes and demo notebooks.)
  * added `.travis.yml` in the skip list but I am unsure about this one.
  * json format can not have comment, so can not explain why these files are in the skip list.  I wish the file format was yml instead. yml provides the same info as json but is more flexible.

* Changes are from cookiecutter fixes (PR https://github.com/bird-house/cookiecutter-birdhouse/pull/85) or manual merge conflict resolution (my first time, I might do it badly, please review).

* Makefile merge with cookiecutter, most complicated manual merge, so here is the diff vs the cookiecutter for comparison https://www.diffnow.com/api/reports/getReport?durationKey=&reportId=eb8abea1-005f-428f-b807-d903787c3f09

* Travis-CI is finally running all the builds (so Makefile changes works) but none of the builds passed !  This will have to be handle in another PR.

## Additional Information

Links to other issues or sources.

### CODE REVIEW

**Comment by tlvu** [comment]
Oh geez, Travis build has not been passing (conda not even installing) since PR https://github.com/Ouranosinc/raven/pull/264 build https://travis-ci.com/github/Ouranosinc/raven/jobs/325979900
```
$ make install
Installing Anaconda ...
Updating conda environment raven ...
"/home/travis/miniconda3/bin/conda" create --yes -n raven python=3.6
/bin/sh: 1: /home/travis/miniconda3/bin/conda: not found
Makefile:72: recipe for target 'conda_env' failed
make: *** [conda_env] Error 127
The command "make install" failed and exited with 2 during .
```

Is that a known error, and that's why we merge PR even with failed build?

**Comment by huard** [comment]
Yes, and instead of trying to debug the error, I thought it was better to update from the cookie-cutter and hope that it would fix the issue.

**Comment by tlvu** [comment]
> Yes, and instead of trying to debug the error, I thought it was better to update from the cookie-cutter and hope that it would fix the issue.

I was hoping to have a working previous build to serve as reference point if I broke something in this PR.

Oh well, I'll start digging then.

**Comment by huard** [comment]
Sorry about that.

**Comment by tlvu** [comment]
`/home/travis/miniconda3/bin/conda run -n raven make start` is hanging on Travis-CI see build https://travis-ci.com/github/Ouranosinc/raven/jobs/337026202, has someone seen this before?

**Comment by tlvu** [comment]
@huard @Zeitsperre All the builds are running on TravisCI now but none of them are passing https://travis-ci.com/github/Ouranosinc/raven/builds/167668875  Can you guys take a look at the multiples failures (unit tests, pep8, docs, notebooks) while I continue working on the cookiecutter update mechanism?

**Comment by huard** [comment]
@tlvu  On it.

**Comment by tlvu** [comment]
FYI TravisCI debug build (https://docs.travis-ci.com/user/running-build-in-debug-mode) been enabled on this Raven repo.  We can ssh inside the TravisCI build VM to manually inspect build failures that we can not reproduce locally.

Also I've left all the multiples attempts to fix TravisCI build failures in the git history as documentation for what works and what doesn't.  I think we should avoid squashing commits because I think there are values in keeping those (ping @Zeitsperre).

**Pull request merged**
