### PR TITLE
docker: fix missing raven binaries in docker image and bump ravenpy to 0.2.3

### PR DESCRIPTION
**Pull request by tlvu**
Also add instructions in the `docker-compose.yml` on how to test a local build of the docker image.

### CODE REVIEW

**Review by huard — APPROVED** [review]

**Review by cjauvin — APPROVED** [review]
je vais approuver mais je pense qu'on devrait explorer l'option de gérer les binaires raven directement dans le Dockerfile (sans le faire via pip ou conda)

**Comment by tlvu** [comment]
@huard New warnings from docker image built from this PR.

```
/opt/conda/envs/wps/lib/python3.8/site-packages/ravenpy/utilities/gis.py:257: RuntimeWarning: Sequential read of iterator was interrupted. Resetting i
terator. This can negatively impact the performance.                                                                                                  
  for _ in coll.filter(bbox=bbox):                                                                                                                    
/opt/wps/raven/processes/wps_hydrobasins_shape_selection.py:105: RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This
 can negatively impact the performance.                                                                                                               
  feat = next(iter(src))                                                                                                                              
/opt/conda/envs/wps/lib/python3.8/site-packages/pyproj/crs/crs.py:280: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<c
ode>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotcha
s.html#axis-order-changes-in-proj-6                                                                                                                   
  projstring = _prepare_from_string(projparams)
```

@cjauvin Confirmed ravenpy `0.2.3` fixes all "missing binaries" errors from notebooks tests.

**Comment by cjauvin** [comment]
@tlvu actually 0.2.3 should fix errors about RAVENPY_TESTDATA_PATH :thinking:

**Comment by tlvu** [comment]
> @tlvu actually 0.2.3 should fix errors about RAVENPY_TESTDATA_PATH thinking

@cjauvin yes that's what I meant.  My brain is mixed up with too many permutations of errors right now.

**Comment by Zeitsperre** [comment]
> @huard New warnings from docker image built from this PR.
> 
> ```
> /opt/conda/envs/wps/lib/python3.8/site-packages/ravenpy/utilities/gis.py:257: RuntimeWarning: Sequential read of iterator was interrupted. Resetting i
> terator. This can negatively impact the performance.                                                                                                  
>   for _ in coll.filter(bbox=bbox):                                                                                                                    
> /opt/wps/raven/processes/wps_hydrobasins_shape_selection.py:105: RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This
>  can negatively impact the performance.                                                                                                               
>   feat = next(iter(src))                                                                                                                              
> /opt/conda/envs/wps/lib/python3.8/site-packages/pyproj/crs/crs.py:280: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<c
> ode>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotcha
> s.html#axis-order-changes-in-proj-6                                                                                                                   
>   projstring = _prepare_from_string(projparams)
> ```
> 
> @cjauvin Confirmed ravenpy `0.2.3` fixes all "missing binaries" errors from notebooks tests.

@tlvu I'm currently updating the GIS-side of RAVEN/RavenPy. `pyproj` has been simplified quite a bit, so I'll hopefully be able to remove these new warning in https://github.com/Ouranosinc/raven/pull/335 and https://github.com/CSHS-CWRA/RavenPy/pull/39

**Pull request merged**
