### PR TITLE
Update Raven version [WIP]

### LINKED ISSUE #222: Update Raven to rev 251
## Description

- New version of Raven allowing for YYYY-MM-DD time units, assuming 00:00:00. 
- Bug fix to PET_OUDIN, expect changes to outputs

### PR DESCRIPTION
**Pull request by huard**
## Overview

This PR fixes #222, #145

Changes:

* Raven version is now 254

## Related Issue / Discussion
To rebuild: 
```
make raven_clean
make raven_dev
```

## Additional Information
Lots of failing tests... need to understand what changed. 

Links to other issues or sources.

### CODE REVIEW

**Comment by julemai** [comment]
The PET_OUDIN implementation changed since we found a bug in there. So, all models that use that PET option (in RVI) will give different results.

**Comment by richardarsenault** [comment]
I've checked and fixed all failing tests except one: In test_emulators.py, there is a test for HMETS_OST where we calibrate HMETS (with fixed seed) and then rerun HMETS with the optimized parameter set. However there is a small difference in NSE, like if there was a difference of 1 day in the simulation, but the tests seem setup correctly. Need to investigate this further.

**Comment by richardarsenault** [comment]
Fixed, now all passes.

**Comment by huard** [comment]
I think we'd better merge this even though the travis build is broken.

**Comment by richardarsenault** [comment]
I agree, merging.

**Pull request merged**
