### PR TITLE
Travis tweak

### PR DESCRIPTION
**Pull request by huard**
## Overview

- Name for builds. 
- Separate build for PEP8.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
I can take it from here. ;)

**Comment by huard** [comment]
Ok, that's my last try then I'll leave it to you.

**Comment by huard** [comment]
I installed travis locally, and there is a `travis lint` bash script to check the validity of travis config files.

**Comment by Zeitsperre** [comment]
Just noting here but the travis ruby tool doesn't install very cleanly in some machines due to the deprecation of `rubygems` (ie: broken in cutting-edge Linux distros). Travis CI is releasing a new version soon.

**Comment by Zeitsperre** [comment]
Pretty happy with the results here. @huard Looking at the C compiler problems makes me think we could consider collecting the RAVEN source code and making a build for macOS and Linux from source. Perhaps not now but down the line.

**Comment by julemai** [comment]
Sorry I lost a bit track here. Which kind of C compiler problems do you have? Is it due to Raven? I just know that distributing an executable is usually hard when NetCDF is included.

**Comment by huard** [comment]
Another option is to use a docker image of the build. Marc Lalonde has already prepared something, I need to take a look.

**Pull request merged**
